apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: flux-system
  namespace: flux-system
spec:
  force: false
  interval: 1m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
